version: "3.7"

services:
    web-educasis:
        image: "mdobes/educa-sis:lastest"
        container_name: "web-educasis"
        restart: "always"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web-educasis-sec.entrypoints=websecure"
            - "traefik.http.routers.web-educasis-sec.rule=Host(`educasis.dobes.pw`)"
            - "traefik.http.routers.web-educasis-sec.tls.certresolver=cf-auto"
        volumes:
            - ./files/:/var/www/html/
networks:
    default:
        external:
            name: "webhosting"
