version: "3.7"

services:
    web-educasis:
        image: "mdobes/educa-sis:lastest"
        build:
            context: .
            args:
                BASE_TAG: latest
                network: default
        container_name: "web-educasis"
        ports:
            - 80:80
        restart: "always"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        volumes:
            - ./:/var/www/html/
        networks:
            - "default"
        #entrypoint: "php /var/www/html/artisan migrate --force"
networks:
    default:
        external: true
        name: "webhosting"
