version: "3.7"

services:
    web-educasis:
        image: "mdobes/educa-sis:lastest"
        build:
            context: .
            args:
                BASE_TAG: latest
                network: default
        container_name: "web-educasis"
        ports:
            - 80:80
        restart: "always"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        volumes:
            - ./:/var/www/html/
            - ./.docker/ldap.conf:/etc/ldap/ldap.conf
        networks:
            - "default"
        #command: bash -c "php /var/www/html/artisan queue:work --timeout=90 & while true; do php /var/www/html/artisan schedule:run --verbose --no-interaction; sleep 60; done"
networks:
    default:
        external: true
        name: "webhosting"
