version: "3.7"

services:
    web-educasis:
        image: "mdobes/educa-sis:lastest"
        build:
            context: .
            args:
                BASE_TAG: latest
                network: default
        container_name: "web-educasis"
        ports:
            - 80:80
        restart: "always"
        volumes:
            - ./:/var/www/html/
            - ./.docker/ldap.conf:/etc/ldap/ldap.conf
            - ./.docker/supervisor.conf:/etc/supervisor/conf.d/worker.conf
        networks:
            - "default"
networks:
    default:
        external: true
        name: "webhosting"
